name: CICD Main Reusable
on:
  workflow_call:

jobs:
  docker_build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: Build Image
        run: make docker-build image_tag=${GITHUB_SHA}

  test:
    runs-on: self-hosted
    needs: docker_build
    steps:
      - name: Run Tests
        run: echo "Running tests..."


  # dev-deploy:
  #   runs-on: self-hosted
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: actions/checkout@v6
  #       with:
  #         repository: raghudevopsb88/wmp-helm-v1
  #         path: helm
  #     - name: Helm Deploy
  #       run: |
  #         aws eks update-kubeconfig --name dev
  #         argocd_admin_password=$(kubectl get secrets argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d)
  #         make argocd-deploy image_tag=${GITHUB_SHA} argocd_server=argocd-dev.raghudevopsb88.online argocd_admin_password=${argocd_admin_password}


  qa-deploy:
    runs-on: self-hosted
    needs: dev-deploy
    environment: qa
    steps:
      - name: Deploy to QA
        run: echo "Deploying to QA..."


  uat-deploy:
    runs-on: self-hosted
    needs: qa-deploy
    environment: uat
    steps:
      - name: Deploy to UAT
        run: echo "Deploying to UAT..."


  prod-deploy:
    runs-on: self-hosted
    needs: uat-deploy
    environment: prod
    steps:
      - name: Deploy to Production
        run: echo "Deploying to production..."

